### ISSUE TITLE
boto3 exception while uploading to s3 (ie minio)

### ISSUE THREAD

**Issue by ZeroGraviti** [kylegallatin/mlops-pipeline#3]
Not sure what is causing this... its going into a retry loop while uploading the model (last line of `train.py`)

 ```
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the UploadPart operation (reached max retries: 4): We encountered an internal error, please try again.: cause(open /data/.minio.sys/multipart/e6d54367be63439526ba5ac8a5ac19f7f5f5dcb42b2e50b1e9fd507a3a929b01/ec0cf316-457e-4071-a897-03e29ff08c56/fs.json: invalid argument)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 36, in <module>
    mlflow.sklearn.log_model(model, "rf-regressor")
  File "/usr/local/lib/python3.7/site-packages/mlflow/sklearn/__init__.py", line 341, in log_model
    extra_pip_requirements=extra_pip_requirements,
  File "/usr/local/lib/python3.7/site-packages/mlflow/models/model.py", line 188, in log
    mlflow.tracking.fluent.log_artifacts(local_path, artifact_path)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 584, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 977, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 334, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 108, in log_artifacts
    key=posixpath.join(upload_path, f),
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 80, in _upload_file
    s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/inject.py", line 132, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 287, in upload_file
    filename, '/'.join([bucket, key]), e))
boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/tmpjp_ilq42/model/model.pkl to mlflow/1/95bea0a7edc84591b1f297a3c228ccac/artifacts/rf-regressor/model.pkl: An error occurred (InternalError) when calling the UploadPart operation (reached max retries: 4): We encountered an internal error, please try again.: cause(open /data/.minio.sys/multipart/e6d54367be63439526ba5ac8a5ac19f7f5f5dcb42b2e50b1e9fd507a3a929b01/ec0cf316-457e-4071-a897-03e29ff08c56/fs.json: invalid argument)
```

**Comment by ZeroGraviti** [comment]
.
